//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Degage.ServiceModel.Rpc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceModelTextDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceModelTextDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Degage.ServiceModel.Rpc.ServiceModelTextDescription", typeof(ServiceModelTextDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 元数据缓存操作失败！.
        /// </summary>
        internal static string Exception_Desc_0001 {
            get {
                return ResourceManager.GetString("Exception_Desc_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未能加载服务结构信息！.
        /// </summary>
        internal static string Exception_Desc_2000 {
            get {
                return ResourceManager.GetString("Exception_Desc_2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此接口类型未标识为服务接口！.
        /// </summary>
        internal static string Exception_Desc_2001 {
            get {
                return ResourceManager.GetString("Exception_Desc_2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此方法未被标识为服务操作！.
        /// </summary>
        internal static string Exception_Desc_2002 {
            get {
                return ResourceManager.GetString("Exception_Desc_2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务实现类型与接口类型不匹配！.
        /// </summary>
        internal static string Exception_Desc_3000 {
            get {
                return ResourceManager.GetString("Exception_Desc_3000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-{1} 与 {2}-{3} 的服务操作路径相同！.
        /// </summary>
        internal static string Exception_Desc_3001 {
            get {
                return ResourceManager.GetString("Exception_Desc_3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序列化异常！.
        /// </summary>
        internal static string Exception_Desc_4001 {
            get {
                return ResourceManager.GetString("Exception_Desc_4001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务通信异常！.
        /// </summary>
        internal static string Exception_Desc_5001 {
            get {
                return ResourceManager.GetString("Exception_Desc_5001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未能找到服务操作参数的序列化器的类型信息！.
        /// </summary>
        internal static string Exception_Desc_6001 {
            get {
                return ResourceManager.GetString("Exception_Desc_6001", resourceCulture);
            }
        }
    }
}
